name: master
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setupJava
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: 'gradle'
    - name: Check
      run: ./gradlew check
